CUDA_VISIBLE_DEVICES=0 python train.py \
	--domain_name pick-place-v1 \
	--task_name pick_place \
	--cameras 2 \
	--observation_type pixel \
	--encoder_type pixel \
	--save_tb --save_video --save_model \
	--pre_transform_image_size 100 --image_size 84 \
	--work_dir ./data/pick-place \
	--agent curl_sac --frame_stack 3 \
	--seed -1 --critic_lr 1e-3 --actor_lr 1e-3 \
	--eval_freq 10000 --batch_size 128 --num_train_steps 2000000
